### ISSUE TITLE
Where are data set and commands?

### ISSUE THREAD

**Issue by clopezno** [SAILResearch/replication-stackoverflow_topics_trends#1]
In readme file is said:
"Stack Overflow posts, topics, trends, and commands (1.7GB) can be downloaded here
We include a README file to describe the contents."

I click in the here link but I don´t see dataset,topics, commands...

Greetings 
Carlos López

**Comment by golivax** [comment]
Hi Carlos. Looking into it...

**Comment by clopezno** [comment]
Hi  golivax
In this link https://github.com/SAILResearch/replication-stackoverflow_topics_trends/releases I just can see this
![githubbug](https://user-images.githubusercontent.com/1453744/41667440-4bd49b4c-74ad-11e8-88b7-3ceb2211160b.PNG)

**Comment by clopezno** [comment]
Golivax, can you access to code and to data set?
Greetings

**Comment by golivax** [comment]
Due to an internal infrastructure problem, the replication package is not available anymore. However, the data originally employed in our study should be somewhat easily obtainable from Stack Overflow dumps and archives, such as https://data.stackexchange.com/ and https://archive.org/details/stackexchange. Thanks and really sorry for the inconvenience!
